In [1]:
import numpy as np

## Numpy -->

It is fundamental library for numerical computing and it is also known as 'Numerical Python'.

- It provides
1. Efficient Multidimentional array objects
2. A Large collection of High-level Mathematical functions.

In [3]:
lst = [1,2,3,4]
arr = np.array(lst).reshape(2,2)
arr

array([[1, 2],
       [3, 4]])

In [8]:
## Create an Array of 1 to 100 numbers. Using the list comprehension
num = [i for i in range(1,101)]
arr = np.array(num)
arr

# for checking the dimension of array
arr.ndim

# for getting the rows and columns in a array
arr.shape

(100,)

In [13]:
li = [[1,2,3], [4,5,6], [7,8,9]]
arr = np.array(li).reshape(3,3)
arr.shape       ## checking the shape of data

arr.ndim        ## checking the dimension

arr.size        ## checking the number of elements

9

In [15]:
## 5 x 5 ----> shape, dimension and size
arr = np.random.randint(1,100,25).reshape(5,5)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[66 32 58 37 28]
 [19 94 78 23 24]
 [95 12 29 75 89]
 [10 16 19 81 72]
 [89 12 18 47  8]]
(5, 5)
2
25
